#!/bin/bash

check() {
    require_binaries "$WORK_DIR/gosquito" || return 1
    return 255
}

depends() {
    echo "base"
    return 0
}

install() {
    inst "/bin/cat"
    inst "/usr/bin/top"
    inst "$WORK_DIR/gosquito" "/usr/local/bin/gosquito"
}