#!/bin/bash

check() {
    require_binaries "$WORK_DIR/gosquito" || return 1
    return 255
}

depends() {
    echo "base" "debug"
    return 0
}

install() {
    mapfile -t -d '' _filenames < <(find /usr/share/i18n -type f -print0)
    inst_multiple "${_filenames[@]}"

    mapfile -t -d '' _filenames < <(find /usr/lib/gconv -type f -print0)
    inst_multiple "${_filenames[@]}"

    inst "$WORK_DIR/gosquito" "/usr/local/bin/gosquito"
}
